# Generated by Django 2.2.7 on 2019-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_img',
            field=models.ImageField(default='', upload_to='sairweb/images/destination_img'),
        ),
    ]
