# Generated by Django 2.2.7 on 2019-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0002_destination_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
