# Generated by Django 2.2.7 on 2019-11-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0003_auto_20191126_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination_img',
            new_name='dest_img',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='destination_name',
            new_name='dest_name',
        ),
    ]
