# Generated by Django 2.2.7 on 2019-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0005_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pkg_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
