# Generated by Django 2.2.7 on 2019-12-04 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0006_auto_20191127_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
