# Generated by Django 2.2.7 on 2019-12-05 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0007_package_pkg_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
