# Generated by Django 2.2.7 on 2019-12-17 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0009_wadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='visaInfo',
            fields=[
                ('visa_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_no', models.CharField(default='', max_length=50)),
                ('fname', models.CharField(default='', max_length=50)),
                ('passport_no', models.CharField(default='', max_length=50)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('visa_type', models.CharField(default='', max_length=50)),
                ('visa_status', models.CharField(default='', max_length=50)),
                ('visa_img', models.ImageField(default='', upload_to='sairweb/images/visa_img')),
            ],
        ),
    ]
