# Generated by Django 2.2.7 on 2019-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0010_visainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='visa_status',
        ),
    ]
