# Generated by Django 2.2.7 on 2019-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0011_remove_visainfo_visa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='visa_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
