# Generated by Django 2.2.7 on 2019-12-17 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0012_visainfo_visa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
