# Generated by Django 2.2.7 on 2019-12-17 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0013_auto_20191217_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='date added'),
        ),
    ]
