# Generated by Django 2.2.7 on 2019-12-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0014_auto_20191217_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='dob',
            field=models.DateTimeField(default=''),
        ),
    ]
