# Generated by Django 2.2.7 on 2019-12-17 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0015_auto_20191217_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
