# Generated by Django 2.2.7 on 2019-12-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0016_auto_20191217_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='ref_no',
        ),
    ]
