# Generated by Django 2.2.7 on 2020-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0018_auto_20191224_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='vCountry',
            field=models.CharField(default='', max_length=50),
        ),
    ]
