# Generated by Django 2.2.7 on 2020-01-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0020_visainfo_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='wadmin',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
