# Generated by Django 2.2.7 on 2020-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sairweb', '0021_wadmin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
