from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('test', views.test,name='test'),
    path('about', views.about,name='about'),
    path('contact', views.contact,name='contact'),
    path('destination_list', views.destination_list,name='destination_list'),
    path('package_list', views.package_list,name='package_list'),
    path('add_destination', views.add_destination,name='add_destination'),
    path('add_package', views.add_package,name='add_package'),
    path('packages/<int:pid>', views.packages,name='packages'),
    path('delete_plist_info/<int:lid>',views.delete_plist_info,name="delete_plist_info"),
    path('edit_plist_info/<int:lid>',views.edit_plist_info,name="edit_plist_info"),
    path('update_plist_info/<int:lid>',views.update_plist_info,name="update_plist_info"),
    path('admin_signin', views.admin_signin,name='admin_signin'),
    path('admin_signup', views.admin_signup,name='admin_signup'),
    path('signup', views.signup,name='signup'),
    path('signin', views.signin,name='signin'),
    path('logout', views.logout,name='logout'),
    path('wadmin_index', views.wadmin_index,name='wadmin_index'),
    path('delete_dlist_info/<int:lid>', views.delete_dlist_info, name="delete_dlist_info"),
    path('edit_dlist_info/<int:lid>', views.edit_dlist_info, name="edit_dlist_info"),
    path('update_dlist_info/<int:lid>', views.update_dlist_info, name="update_dlist_info"),
    path('visaTrackingEdit', views.visaTrackingEdit,name='visaTrackingEdit'),
    path('visaTrackingView', views.visaTrackingView,name='visaTrackingView'),
    path('visaTrackingUser', views.visaTrackingUser,name='visaTrackingUser'),
    path('visaTrackingList', views.visaTrackingList,name='visaTrackingList'),
    path('visaTrackingDelete/<int:vid>', views.visaTrackingDelete, name="visaTrackingDelete"),
    path('visaTrackingUpdateView/<int:vid>', views.visaTrackingUpdateView, name="visaTrackingUpdateView"),
    path('visaTrackingUpdate/<int:vid>', views.visaTrackingUpdate, name="visaTrackingUpdate"),
    path('packageShow', views.packageShow, name="packageShow"),
    path('visa_Filedelete/<int:vid>/<int:fid>', views.visa_Filedelete, name="visa_Filedelete"),
    path('aviation', views.aviation, name="aviation"),
    path('visa_requirements/<int:rid>', views.visa_requirements, name="visa_requirements"),
    path('visa_country', views.visa_country, name="visa_country"),
    path('sentMail', views.sentMail, name="sentMail"),
    path('sentMailCustom', views.sentMailCustom, name="sentMailCustom"),
    path('modarator_list', views.modarator_list, name="modarator_list"),
    path('edit_mlist_info/<int:lid>', views.edit_mlist_info, name="edit_mlist_info"),
    path('update_mlist_info/<int:lid>', views.update_mlist_info, name="update_mlist_info"),
    path('delete_mlist_info/<int:lid>', views.delete_mlist_info, name="delete_mlist_info"),
    path('destinations', views.destinations, name="destinations"),

]
